## E-Commerce Sales Data Cleaning

### 1. Import Library

In [1]:
import pandas as pd

### 2. Load The Dataset

In [2]:
df = pd.read_csv('E-Commerce Original Dataset.csv')
print("Dataset Loaded Successfully.")

Dataset Loaded Successfully.

### 3. View The Dataset

##### Dataset : Head View

In [3]:
print('Dataset View: Head Part')
df.head()

Dataset View: Head Part

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,Uttar Pradesh,North,NaN,Monitor,Electronics,300.0,5,1500,13.31,Returned,08-12-2023
1,CUST0046,Male,Maharashtra,West,22.0,Earbuds,Accessories,100.0,2,200,6.93,In Transit,09-04-2023
2,CUST0169,Female,Bihar,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,28-08-2023
3,CUST0002,Male,West Bengal,North,23.0,Earbuds,Accessories,100.0,5,500,12.22,Delivered,18-01-2023
4,CUST0173,Female,Madhya Pradesh,South,NaN,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,19-01-2023

##### Dataset : Tail View

In [4]:
print('Dataset View: Tail Part')
df.tail()

Dataset View: Tail Part

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
995,CUST0201,Female,Meghalaya,South,49.0,Earbuds,Accessories,100.0,1,100,17.21,In Transit,05-01-2023
996,CUST0133,Male,Manipur,East,47.0,Laptop,Electronics,1500.0,1,1500,19.19,Delivered,01-04-2023
997,CUST0055,Female,Nagaland,North,NaN,Mouse,Accessories,30.0,5,150,19.35,Delivered,20-10-2023
998,CUST0023,Female,Goa,South,29.0,Laptop,Electronics,1500.0,5,7500,10.36,Returned,07-01-2023
999,CUST0040,Male,Arunachal Pradesh,NaN,29.0,Watch,Wearables,200.0,1,200,7.53,Delivered,30-01-2023

### 4. Check Dataset Structure

##### Dataset Column Names

In [5]:
columns = df.columns
print('All Columns in Dataset:\n\n',columns)

All Columns in Dataset:

 Index(['Customer ID', 'Gender', 'State', 'Region', 'Age', 'Product Name',
       'Category', 'Unit Price', 'Quantity', 'Total Price', 'Shipping Fee',
       'Shipping Status', 'Order Date'],
      dtype='str')

##### Dataset Shape

In [6]:
print('Dataset Shape:', df.shape)

Dataset Shape: (1000, 13)

##### Change the Data Type

In [7]:
median = df['Age'].median()
df['Age'] = df['Age'].fillna(median).astype(int)
df['Total Price'] = df['Total Price'].astype(float)
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
print("Data Types Changed Successfully.")

Data Types Changed Successfully.

##### Dataset Information

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer ID      1000 non-null   str
 1   Gender           1000 non-null   str
 2   State            1000 non-null   str
 3   Region           950 non-null    str
 4   Age              1000 non-null   int64
 5   Product Name     1000 non-null   str
 6   Category         1000 non-null   str
 7   Unit Price       1000 non-null   float64
 8   Quantity         1000 non-null   int64
 9   Total Price      1000 non-null   float64
 10  Shipping Fee     1000 non-null   float64
 11  Shipping Status  950 non-null    str
 12  Order Date       1000 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(2), str(7)
memory usage: 101.7 KB

### 5. Generate Summary Statistics

In [9]:
print("Statistical Summary:")
df[['Age', 'Quantity', 'Unit Price', 'Total Price', 'Shipping Fee']].describe()

Statistical Summary:

               Age     Quantity   Unit Price  Total Price  Shipping Fee
count  1000.000000  1000.000000  1000.000000  1000.000000   1000.000000
mean     46.926000     3.008000   457.703777  1346.600000     12.416390
std      14.257061     1.404246   537.231434  1834.037877      4.412185
min      18.000000     1.000000    30.000000    30.000000      5.000000
25%      37.000000     2.000000    50.000000   200.000000      8.560000
50%      49.000000     3.000000   200.000000   600.000000     12.315000
75%      58.000000     4.000000   800.000000  1500.000000     16.075000
max      69.000000     5.000000  3109.560612  7500.000000     19.980000

### 6. Detect & Handle Missing Values

In [10]:
df.isnull()

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,True,False,False,False,False,False,False,False,False,False

In [11]:
df.dropna()

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,Uttar Pradesh,North,49,Monitor,Electronics,300.0,5,1500.0,13.31,Returned,2023-12-08
1,CUST0046,Male,Maharashtra,West,22,Earbuds,Accessories,100.0,2,200.0,6.93,In Transit,2023-04-09
2,CUST0169,Female,Bihar,South,54,Monitor,Electronics,300.0,1,300.0,11.31,Returned,2023-08-28
3,CUST0002,Male,West Bengal,North,23,Earbuds,Accessories,100.0,5,500.0,12.22,Delivered,2023-01-18
4,CUST0173,Female,Madhya Pradesh,South,49,Laptop,Electronics,1500.0,3,4500.0,5.40,Delivered,2023-01-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,CUST0079,Male,Tripura,West,26,Watch,Wearables,200.0,2,400.0,7.14,Returned,2023-01-04
995,CUST0201,Female,Meghalaya,South,49,Earbuds,Accessories,100.0,1,100.0,17.21,In Transit,2023-01-05
996,CUST0133,Male,Manipur,East,47,Laptop,Electronics,1500.0,1,1500.0,19.19,Delivered,2023-04-01
997,CUST0055,Female,Nagaland,North,49,Mouse,Accessories,30.0,5,150.0,19.35,Delivered,2023-10-20
998,CUST0023,Female,Goa,South,29,Laptop,Electronics,1500.0,5,7500.0,10.36,Returned,2023-01-07

In [12]:
df.dropna(subset=['Region', 'Shipping Status'], inplace=True)

### 7. Detect & Remove Duplicate Records

In [13]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
994    False
995    False
996    False
997    False
998    False
Length: 901, dtype: bool

In [14]:
df.drop_duplicates()

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,Uttar Pradesh,North,49,Monitor,Electronics,300.0,5,1500.0,13.31,Returned,2023-12-08
1,CUST0046,Male,Maharashtra,West,22,Earbuds,Accessories,100.0,2,200.0,6.93,In Transit,2023-04-09
2,CUST0169,Female,Bihar,South,54,Monitor,Electronics,300.0,1,300.0,11.31,Returned,2023-08-28
3,CUST0002,Male,West Bengal,North,23,Earbuds,Accessories,100.0,5,500.0,12.22,Delivered,2023-01-18
4,CUST0173,Female,Madhya Pradesh,South,49,Laptop,Electronics,1500.0,3,4500.0,5.40,Delivered,2023-01-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,CUST0079,Male,Tripura,West,26,Watch,Wearables,200.0,2,400.0,7.14,Returned,2023-01-04
995,CUST0201,Female,Meghalaya,South,49,Earbuds,Accessories,100.0,1,100.0,17.21,In Transit,2023-01-05
996,CUST0133,Male,Manipur,East,47,Laptop,Electronics,1500.0,1,1500.0,19.19,Delivered,2023-04-01
997,CUST0055,Female,Nagaland,North,49,Mouse,Accessories,30.0,5,150.0,19.35,Delivered,2023-10-20
998,CUST0023,Female,Goa,South,29,Laptop,Electronics,1500.0,5,7500.0,10.36,Returned,2023-01-07

### 8. Correct Data Types

In [15]:
df['Unit Price'] = df['Unit Price'].round(2)
df['Total Price'] = df['Total Price'].round(2)
df['Shipping Fee'] = df['Shipping Fee'].round(2)

### 9. Standardize Text Data

In [16]:
columns = ['Customer ID', 'Gender', 'Region', 'Product Name', 'Category', 'Shipping Status']
df[columns] = df[columns].apply(lambda x: x.str.strip())
df[columns] = df[columns].apply(lambda x: x.str.title())
print("Text Cleaned Successfully.")

Text Cleaned Successfully.

### 10. Detect & Handle Outliers

##### Outlier Limits Using The IQR Method

In [17]:
num_columns = df.select_dtypes(include='number')

Q1 = num_columns.quantile(0.25)
Q3 = num_columns.quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print("Lower Limit:\n",round(lower,3))
print("\nUpper Limit:\n",round(upper,3))

Lower Limit:
 Age                5.500
Unit Price     -1075.000
Quantity          -1.000
Total Price    -1750.000
Shipping Fee      -2.735
dtype: float64

Upper Limit:
 Age               89.500
Unit Price      1925.000
Quantity           7.000
Total Price     3450.000
Shipping Fee      27.305
dtype: float64

##### Detect Outliers - Head View

In [18]:
outliers = df[(num_columns < lower) | (num_columns > upper)]
print('Detect Outliers: Head Part:')
outliers.head()

Detect Outliers: Head Part:

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500.0,NaN,NaN,NaT

##### Detect Outliers - Tail View

In [19]:
print('\nDetect Outliers: Tail Part')
outliers.tail()

Detect Outliers: Tail Part

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7500.0,NaN,NaN,NaT

#### Remove Outliers In Dataset

In [20]:
df = df[((num_columns >= lower) & (num_columns <= upper)).all(axis=1)]
df.head()

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,Cust0268,Male,Uttar Pradesh,North,49,Monitor,Electronics,300.0,5,1500.0,13.31,Returned,2023-12-08
1,Cust0046,Male,Maharashtra,West,22,Earbuds,Accessories,100.0,2,200.0,6.93,In Transit,2023-04-09
2,Cust0169,Female,Bihar,South,54,Monitor,Electronics,300.0,1,300.0,11.31,Returned,2023-08-28
3,Cust0002,Male,West Bengal,North,23,Earbuds,Accessories,100.0,5,500.0,12.22,Delivered,2023-01-18
5,Cust0147,Male,Tamil Nadu,North,64,Watch,Wearables,200.0,2,400.0,11.26,In Transit,2023-01-11

In [21]:
df.tail()

,Customer ID,Gender,State,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
993,Cust0200,Female,Himachal Pradesh,North,68,Phone,Electronics,800.0,4,3200.0,17.32,Returned,2023-08-05
994,Cust0079,Male,Tripura,West,26,Watch,Wearables,200.0,2,400.0,7.14,Returned,2023-01-04
995,Cust0201,Female,Meghalaya,South,49,Earbuds,Accessories,100.0,1,100.0,17.21,In Transit,2023-01-05
996,Cust0133,Male,Manipur,East,47,Laptop,Electronics,1500.0,1,1500.0,19.19,Delivered,2023-04-01
997,Cust0055,Female,Nagaland,North,49,Mouse,Accessories,30.0,5,150.0,19.35,Delivered,2023-10-20

### 11. Verify The Cleaned Dataset

##### Dataset Shape

In [22]:
shape = df.shape
print('Dataset Shape:',shape)

Dataset Shape: (786, 13)

##### Check Missing Values

In [23]:
df.isnull().sum()

Customer ID        0
Gender             0
State              0
Region             0
Age                0
Product Name       0
Category           0
Unit Price         0
Quantity           0
Total Price        0
Shipping Fee       0
Shipping Status    0
Order Date         0
dtype: int64

##### Check Duplicate Values

In [24]:
df.duplicated().sum()

np.int64(0)

##### Dataset Information

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 786 entries, 0 to 997
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer ID      786 non-null    str
 1   Gender           786 non-null    str
 2   State            786 non-null    str
 3   Region           786 non-null    str
 4   Age              786 non-null    int64
 5   Product Name     786 non-null    str
 6   Category         786 non-null    str
 7   Unit Price       786 non-null    float64
 8   Quantity         786 non-null    int64
 9   Total Price      786 non-null    float64
 10  Shipping Fee     786 non-null    float64
 11  Shipping Status  786 non-null    str
 12  Order Date       786 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(2), str(7)
memory usage: 86.0 KB

##### 12. Save The Cleaned Dataset

In [26]:
Cleaning = 'E-Commerce Cleaned Dataset.csv'
df.to_csv(Cleaning,index=False)